### ISSUE TITLE
npm run shows missing script

### ISSUE THREAD

**Issue by wojciech-gorski-smt** [happypoulp/redux-tutorial#107]
I followed the instructions in the README so what I did is:

```
npm install
npm run example 01_simple-action-creator.js
```

but it gives me the error:

```
...
npm ERR! missing script: 01_simple-action-creator.js
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/redux-tutorial/npm-debug.log
```

Why am I getting this error?

**Comment by happypoulp** [comment]
Hi,

Sorry for the very late response. Do you still have this issue or are you still interested in investigating this issue?

Thanks.

**Comment by qhaqq-amplify** [comment]
I am having the same issue, and while I'm on the topic, how does one start the webpack server in the 11_src/ directory?

**Comment by happypoulp** [comment]
Can you paste the complete output you get when running `npm run example 01_simple-action-creator.js` please?

As for the example 11 you run it like all other examples by executing:

`npm run example 11_Provider-and-connect.js`

**Comment by qhaqq-amplify** [comment]
`npm ERR! Darwin 16.3.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "01_simple-action-creator.js"`
`npm ERR! node v6.9.4`
`npm ERR! npm  v3.10.10`

`npm ERR! missing script: 01_simple-action-creator.js`
`npm ERR! `
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/user/redux-tutorial/npm-debug.log`

**Comment by happypoulp** [comment]
Thanks, this is very weird... I guess that you can't run any example actually?

Can you try to run `npm run --verbose example 01_simple-action-creator.js` (same command but more verbose) and paste the output please?

Thanks!

**Comment by happypoulp** [comment]
Ok, I see the issue. You're running `npm run 01_simple-action-creator.js` instead of `npm run example 01_simple-action-creator.js`. For all examples, you have to run always run  `npm run example <example_file_name>`.
