### ISSUE TITLE
A link doesn't work at 01_simple-action-creator.js

### ISSUE THREAD

**Issue by quangnd** [happypoulp/redux-tutorial#109]
I'm following your tutorial and find out a link hasn't worked

// Read more about actions and action creators here:
// http://rackt.org/redux/docs/recipes/ReducingBoilerplate.html

Please update or remove it because it didn't make sense.

**Comment by pankajpatel** [comment]
Hi,
A [PR](https://github.com/happypoulp/redux-tutorial/pull/112) has been opened to correct links in the repo.
Please wait for it to get merged.

**Comment by happypoulp** [comment]
Fixed in https://github.com/happypoulp/redux-tutorial/pull/112 , thanks @pankajpatel !
