### ISSUE TITLE
Where's last example?

### ISSUE THREAD

**Issue by uinz** [happypoulp/redux-tutorial#35]
Hello, I want to know where could I find `last example`, thanks.

**Comment by happypoulp** [comment]
Hi!

It's not written yet ;) (the `// TODO` before and after that paragraph might have been a bit confusing but it was a reminder for me to finish it). I'll try to add it soon.

Leaving this issue open until then...

**Comment by ayhoung** [comment]
+1 great stuff!

**Comment by uinz** [comment]
thanks, i learned so much from your tutorial

**Comment by swelet** [comment]
Thanks for all your work, really a great and easy to follow tutorial. The last example of how to glue redux and react together with connect and provide would in my opinon make this THE redux or even THE flux tutorial on the web. I've read a few.
