### ISSUE TITLE
why does the middleware have three levels

### ISSUE THREAD

**Issue by mukeshsoni** [happypoulp/redux-tutorial#48]
Why does the second level function (which is passed the `next` function ref) needed? The way applyMiddleware works, the dispatch functions returned by the middleware are stored as such - 

```
store.dispatch = middleware(store)(store.dispatch);
```

Why can't the `next` be simply passed as the second parameter in the first middleware function call?

**Comment by gaearon** [comment]
No particular reason. We might choose to fix this later: https://github.com/rackt/redux/pull/784

**Comment by mukeshsoni** [comment]
got it. Thanks!
