### ISSUE TITLE
Promise-middleware.js

### ISSUE THREAD

**Issue by banderson5144** [happypoulp/redux-tutorial#55]
Quick question about this file. Is this is generated or is it a template or is it something that has to be written independently?

Just overall review, this tutorial has been amazing and I would love to donate if possible.

**Comment by happypoulp** [comment]
Hi!

This file is not generated, nor is it a template. It is hand-written but it is quite simple. It answers the common issue of handling asynchronous action creators that return promises.

There are high chances that you will at some point need a mechanism to handle asynchronous actions and the presented solution is just one of them (async action creator returning promise handled by a redux middleware). You could then say that when using this solution, such middleware has to be written independently but be advised that there are already many existing implementations that you could take as is (and adapt your action creators consequently):
https://www.npmjs.com/package/redux-promise-middleware
https://github.com/acdlite/redux-promise
This is the one I took inspiration from: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js
...

Hope this helps!

I haven't setup any donation mechanism but thanks a lot for considering that this tutorial could worth it ;).
