### ISSUE TITLE
tutorial 10 link broken in wiki

### ISSUE THREAD

**Issue by tony-kerz** [happypoulp/redux-tutorial#63]
hey man, outstanding tutorial!

i was just following along in the wiki view and the link for tut-10 is broken at the bottom of tut-9.

https://github.com/happypoulp/redux-tutorial/wiki/tutorial-10-middleware

thanks again for the fine work!

**Comment by tony-kerz** [comment]
kk, i fixed up the wiki to add the last few pages, thanks again @happypoulp

**Comment by happypoulp** [comment]
Thanks ;)!
