### ISSUE TITLE
Dependency conflict.

### ISSUE THREAD

**Issue by jngbng** [happypoulp/redux-tutorial#64]
npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-redux@4.0.0 wants react@^0.14.0

"react-dom" may not be compatible with "react".

"react" should be "^0.14.0" instead of  "0.14.0".

**Comment by diffractometer** [comment]
Same

npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-redux@4.0.0 wants react@^0.14.0

**Comment by diffractometer** [comment]
@jngbng changing dep "react-dom" to just "0.14.0" solves problem.

**Comment by happypoulp** [comment]
Thanks for your report, it's fixed now.
