### ISSUE TITLE
the term Subscriber

### ISSUE THREAD

**Issue by JaxCavalera** [happypoulp/redux-tutorial#68]
As I was working through the series, I hit a wall quickly where the term "Subscriber" is used in 2.

I think it would help readers to see the term "reducer" used here instead or at the very least to exchange subscriber for another term that is not reserved in the context of Redux already.

Great series by the way just looking to highlight one area that may improve things further from my experience working through it.

**Comment by happypoulp** [comment]
Hi,

You're right, I need to re-work the n.2 a bit or at least to link it more clearly with n.11. Actually, by using "subscriber" in 2 I really mean the future subscriber we'll be using in:

``` javascript
store.subscribe(function mySubscriber() {
    console.log('The state has changed!')
})
```

So the subscriber I am talking about in 2 is not the reducer, it is the subscriber to state changes. I think I should make it more clear in 2 that the subscriber will not be used until 11 (and that it has nothing to do with reducers).

Is it more clear?

**Comment by JaxCavalera** [comment]
That seems a bit more clear, the only thing that might make it clearer is if instead of introducing the subscriber function inside the store object at Part 2. what if it introduced a basic reducer there and then in Part 11. the subscriber comes in so it keeps the information that's related closer together?

Admittedly, I'm not quite up to Part 11 just yet, I'm working through the 2nd part of the Async Actions  as I type this so once I reach Part 11 it may seem ok but at my current perspective it feels that introducing it only to forget it for 9 lessons may introduce minor confusion as it's difficult to retain all the extra information with no application for using it.

Once the application of a function is clear, then it's easy to remember it because we have a place to put that information where it's relational structure to the rest of the information we are learning can be taken advantage of.

Again, it is your call how you manage the situation, just adding a  few thoughts for possible consideration but I'm not complaining and am very grateful for the time that's been spent developing this series.

**Comment by happypoulp** [comment]
Totally right. I can't quite remember why I tried to introduce "subscriber" concept so early on in the tutorial but the more I think about it the more I agree that it doesn't make any sense :smile:. I'll fix that as soon as possible.

**Comment by JaxCavalera** [comment]
Thanks for being so open about this, even more respect and appreciation for the work you've done. :)

**Comment by happypoulp** [comment]
done in https://github.com/happypoulp/redux-tutorial/commit/c1751dd73476abdf322c0ea8435a37b4e71db10a .

**Comment by JaxCavalera** [comment]
Thank you ^ ^
