### ISSUE TITLE
Error in ...state

### ISSUE THREAD

**Issue by yangfei19881024** [happypoulp/redux-tutorial#93]
Hello,Thanks for your redux-tutorial ,but during my studying with you tutorial , There is a error in 04_get-state.js which is ...state Unexpected token;Can you help me ? Thanks a lot!

**Comment by happypoulp** [comment]
Hi,

How do you run the examples (what command are you using)?

**Comment by yangfei19881024** [comment]
Thanks for answering my question ，I know how to fixed it ! It's ES7 new feature.

**Comment by happypoulp** [comment]
Yes you're supposed to run the examples using `npm run example <example_file.js>` which runs babeljs  for you (the babeljs local to the tutorial, not the one you might have globally installed).
